"""Initial revision

Revision ID: b98d25057475
Revises: 
Create Date: 2021-11-29 00:42:51.800495

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b98d25057475"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "my_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("my_table")
    # ### end Alembic commands ###
