"""Add 2 file errors

Revision ID: e772522154a1
Revises: 74642fb71cb5
Create Date: 2021-11-29 00:44:48.579002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e772522154a1"
down_revision = "74642fb71cb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "myerrors",
        ["INCORRECT_ACCOUNT"],
        ["FILE_NOT_EXISTS", "FILE_NOT_FOUND", "INCORRECT_ACCOUNT"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "myerrors",
        ["FILE_NOT_EXISTS", "FILE_NOT_FOUND", "INCORRECT_ACCOUNT"],
        ["INCORRECT_ACCOUNT"],
    )
    # ### end Alembic commands ###
